$ErrorActionPreference = 'Stop'

Write-Host ""
Write-Host                                                                                   "      Colorized"
Write-Host                                                                                   "      ------------------ "
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'DarkGray'    -BackgroundColor 'Black' " Dim Screen Text    "
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'Gray'        -BackgroundColor 'Black' " Screen Text        "
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'Cyan'        -BackgroundColor 'Black' " Bright Screen Text "
Write-Host ""
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'DarkGray'    -BackgroundColor 'White' " Popup Text         " 
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'Gray'        -BackgroundColor 'White' " Dim Popup Text     " 
Write-Host ""
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'DarkRed'     -BackgroundColor 'Black' " Red                "
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'Blue'        -BackgroundColor 'Black' " Orange             "
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'DarkYellow'  -BackgroundColor 'Black' " Yellow             "
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'DarkGreen'   -BackgroundColor 'Black' " Green              "
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'DarkCyan'    -BackgroundColor 'Black' " Cyan               "
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'DarkBlue'    -BackgroundColor 'Black' " Blue               "
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'Magenta'     -BackgroundColor 'Black' " Violet             "
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'DarkMagenta' -BackgroundColor 'Black' " Magenta            "
Write-Host "" 
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'Red'         -BackgroundColor 'Black' " Traffic Red        "
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'Yellow'      -BackgroundColor 'Black' " Traffic Amber      "
Write-Host -NoNewLine "     "; Write-Host -ForegroundColor 'Green'       -BackgroundColor 'Black' " Traffic Green      "
Write-Host ""
Write-Host                                                                                   "      Color Table"
Write-Host                                                                                   "      ------------------ "
Write-Host -NoNewLine " [00]"; Write-Host -ForegroundColor 'Black'       -BackgroundColor 'Black' " Black              "
Write-Host -NoNewLine " [01]"; Write-Host -ForegroundColor 'DarkBlue'    -BackgroundColor 'Black' " DarkBlue           "
Write-Host -NoNewLine " [02]"; Write-Host -ForegroundColor 'DarkGreen'   -BackgroundColor 'Black' " DarkGreen          "
Write-Host -NoNewLine " [03]"; Write-Host -ForegroundColor 'DarkCyan'    -BackgroundColor 'Black' " DarkCyan           "
Write-Host -NoNewLine " [04]"; Write-Host -ForegroundColor 'DarkRed'     -BackgroundColor 'Black' " DarkRed            "
Write-Host -NoNewLine " [05]"; Write-Host -ForegroundColor 'DarkMagenta' -BackgroundColor 'Black' " DarkMagenta        "
Write-Host -NoNewLine " [06]"; Write-Host -ForegroundColor 'DarkYellow'  -BackgroundColor 'Black' " DarkYellow         "
Write-Host -NoNewLine " [07]"; Write-Host -ForegroundColor 'Gray'        -BackgroundColor 'Black' " Gray               "
Write-Host -NoNewLine " [08]"; Write-Host -ForegroundColor 'DarkGray'    -BackgroundColor 'Black' " DarkGray           "
Write-Host -NoNewLine " [09]"; Write-Host -ForegroundColor 'Blue'        -BackgroundColor 'Black' " Blue (Orange)      "
Write-Host -NoNewLine " [10]"; Write-Host -ForegroundColor 'Green'       -BackgroundColor 'Black' " Green              "
Write-Host -NoNewLine " [11]"; Write-Host -ForegroundColor 'Cyan'        -BackgroundColor 'Black' " Cyan               "
Write-Host -NoNewLine " [12]"; Write-Host -ForegroundColor 'Red'         -BackgroundColor 'Black' " Red                "
Write-Host -NoNewLine " [13]"; Write-Host -ForegroundColor 'Magenta'     -BackgroundColor 'Black' " Magenta (Violet)   "
Write-Host -NoNewLine " [14]"; Write-Host -ForegroundColor 'Yellow'      -BackgroundColor 'Black' " Yellow             "
Write-Host -NoNewLine " [15]"; Write-Host -ForegroundColor 'White'       -BackgroundColor 'White' " White              " 
Write-Host ""
